services:
    rxu.TopicActions.listener:
        class: rxu\TopicActions\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @request
            - @content.visibility
            - @log
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    rxu.TopicActions.cron.task.tidy_topics:
        class: rxu\TopicActions\cron\task\tidy_topics
        arguments:
            - @config
            - @dbal.conn
            - @user
            - @content.visibility
            - @log
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: cron.task }
